### ISSUE TITLE
symbol-cli transaction broken in v0.20.1

### ISSUE THREAD

**Issue by Dawn-Piper** [nemtech/symbol-cli#293]
1. Expected behavior and actual behavior.
Run `symbol-cli transaction` expecting a menu. Instead get 

'/usr/local/lib/node_modules/symbol-cli/build/src/services/sequentialFetcher.service.js:80
    async *createNetworkCallsIterator(addresses) {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/symbol-cli/build/src/commands/transaction/cosign.js:38:37)'

2. Steps to reproduce the problem.
Install symbol-cli v0.20.1
Run 'symbol-cli transaction'

3. Specifications like the version of the project, operating system, or hardware.
Ubuntu Server 18

**Comment by dgarcia360** [comment]
Thanks for reporting the issue.  I believe this is an error thrown by the node version installed. The ``sequencialFetcher`` service uses async generators, which are supported from Node.js 10.  The CLI is [compatible](https://github.com/nemtech/symbol-cli#requirements) with the latest maintained version 12 LTS.

You can check the version installed in your machine with the command ``node --version``. To install Node.js 12 LTS, you can follow the [next instructions](https://nodejs.org/en/download/).

Please, let me know if after updating Node this is solved, or if the command is still not working.

**Comment by Dawn-Piper** [comment]
That's correct. It works now. Thanks.
