### ISSUE TITLE
crash announcing unsigned tx

### ISSUE THREAD

**Issue by mm-s** [nemtech/symbol-cli#363]
1. Expected behavior and actual behavior.
input an unsigned bonded aggregate tx
symbol-cli transaction payload 

crashes this way:
```
TypeError: Cannot read property 'publicKey' of undefined
    at default_1.execute (/usr/local/lib/node_modules/symbol-cli/build/src/commands/transaction/payload.js:78:123)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

2. Steps to reproduce the problem.
symbol-cli transaction payload B8010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001984142E0AB000000000000F2B1B3E609000000824A29052881456BF46EF61D66C5E0D6744FF391FEEFD0F721864C1A6DB1F3791001000000000000510000000000000050AC6D29B7E0BC919D4BC6AC2948E5997D798982A02EBE37BB919DBB7975C0370000000001984C41622A67881210D205202B1E8E524D141D9C22ACA36C73F643B0AE1E9D48D2080D0100000000000000510000000000000050AC6D29B7E0BC919D4BC6AC2948E5997D798982A02EBE37BB919DBB7975C0370000000001984342F3A1E65CA12A80E1A88C186D8BCB63B1DBE6D18B9C4A069E0370717DC757667D0100000000000000590000000000000050AC6D29B7E0BC919D4BC6AC2948E5997D798982A02EBE37BB919DBB7975C037000000000198434116FA8C08995A9B9CD5D455441449386FA92D991C771A4F52CA885475558A6C7901000000B40500000100000000000000

3. Specifications like the version of the project, operating system, or hardware.
Symbol CLI v1.0.0

**Comment by mm-s** [comment]
If the transaction is agg Complete  (not bonded) the crash doesn't happen.
e.g.
```
symbol-cli transaction payload B8010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001984141E0AB000000000000097C9CE8090000002523CE58C4030F76C0DFA763A61DCEB7C0348BBAD5A5E78C185CFF388D1DB1741001000000000000510000000000000050AC6D29B7E0BC919D4BC6AC2948E5997D798982A02EBE37BB919DBB7975C0370000000001984C417400672170875E5D6F6AB5AAA59A1C01AED4C9D6ED47B5191B2F0A63DF0DC8EA0100000000000000510000000000000050AC6D29B7E0BC919D4BC6AC2948E5997D798982A02EBE37BB919DBB7975C0370000000001984342D9684873F5A66DDDE83666D0C494F473A1CDED6F2A41F70A153566E6BEAE3DBC0100000000000000590000000000000050AC6D29B7E0BC919D4BC6AC2948E5997D798982A02EBE37BB919DBB7975C0370000000001984341E0C02BBEA7C0C24217C3FB680DB5191DEA959DE4D18BFE61E1733B985A50739D01000000B40500000100000000000000
```
